core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('shop.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from .import views
app_name = 'shop'
urlpatterns = [
    path('', views.index, name='index'),
    path('products/', views.product_list, name='product_list'),
    path('product/<int:id>/', views.product_detail, name='product_detail'),
    path('create/', views.create_product, name='create_product'),
    path('edit/<int:id>/', views.edit_product, name='edit_product'),
    path('delete/<int:id>/', views.delete_product, name='delete_product'),
    path('add_favorite/<int:product_id>/', views.add_favorite, name='add_favorite'),
    path('remove_favorite/<int:product_id>/', views.remove_favorite, name='remove_favorite'),
    path('favorites/', views.favorite_list, name='favorite_list'),
    path('my-products/', views.my_products, name='my_products'),
    path('reviews/', views.reviews, name='reviews'),
    path('add_review/', views.add_review, name='add_review'),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

shop/models.py
from django.db import models
import datetime
from django.conf import settings

class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField()

    def __str__(self):
        return self.name

class Product(models.Model):
    title = models.CharField(max_length=200, verbose_name='Названня товару')
    description = models.TextField(verbose_name='Опис')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Ціна')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Каталог')
    created_at = models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата публікації')
    contact = models.CharField(max_length=200, verbose_name='Контакти')
    location = models.CharField(max_length=400, verbose_name='Місцезнаходження')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='products')
    image = models.ImageField(blank=True, upload_to='images', verbose_name='Зображення')
    
    def __str__(self):
        return self.title
    
class Favorite(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="favorites")
    product = models.ForeignKey('Product', on_delete=models.CASCADE, related_name="favorited_by")

    class Meta:
        unique_together = ('user', 'product')

    def __str__(self):
        return self.user.username
    
class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="reviews")
    rating = models.PositiveSmallIntegerField(default=5, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Оцінка')
    comment = models.TextField(verbose_name='Відгук')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Review by {self.user.username} on {self.created_at.strftime('%Y-%m-%d')}"

users/models.py
from django.db import models

# Create your models here.

shop/forms.py
from django import forms
from .models import Product, Review, Category

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['title', 'description', 'price', 'created_at', 'contact', 'location', 'category', 'image']

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'comment']

class CategoryFilterForm(forms.Form):
    category = forms.ModelChoiceField(queryset=Category.objects.all(), required=False, label='Категорія')
    query = forms.CharField(max_length=100, required=False, label='Пошук')

shop/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Product, Category, Favorite, Review
from .forms import ProductForm, ReviewForm, CategoryFilterForm
from django.contrib.auth.decorators import login_required

def index(request):
    return render(request, 'shop/index.html')

@login_required
def product_list(request):
    form = CategoryFilterForm(request.GET)
    products = Product.objects.all()  

    if form.is_valid():
        category = form.cleaned_data.get('category')
        query = form.cleaned_data.get('query')

        if category:
            products = products.filter(category=category)

        if query:
            products = products.filter(title__icontains=query)

    return render(request, 'shop/product_list.html', {'products': products, 'form': form})

@login_required
def product_detail(request, id):
    product = Product.objects.get(id=id)
    return render(request, 'shop/product_detail.html', {'product': product})

@login_required
def create_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
           product = form.save(commit=False)
           product.owner = request.user
           product.save()
        return redirect('shop:product_detail', id=product.id)
    else:
        form = ProductForm()
    
    context = {'form': form}
    return render(request, 'shop/create_product.html', context)

@login_required
def edit_product(request, id):
    product = get_object_or_404(Product, id=id)
    if request.user != product.owner and not request.user.is_superuser:
        return redirect('shop:product_list')
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return redirect('shop:product_detail', id=product.id)
    else:
        form = ProductForm(instance=product)

    context = {'form': form, 'product': product}
    return render(request, 'shop/edit_product.html', context)

@login_required
def delete_product(request, id):
    product = get_object_or_404(Product, id=id)
    if request.user != product.owner and not request.user.is_superuser:
        return redirect('shop:product_list')
    if request.method == 'POST':
        product.delete()
        return redirect('shop:product_list')
    
    context = {'product': product}
    return render(request, 'shop/delete_product.html', context)

@login_required
def add_favorite(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    Favorite.objects.get_or_create(user=request.user, product=product)
    return redirect('shop:product_detail', id=product_id)

@login_required
def remove_favorite(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    Favorite.objects.filter(user=request.user, product=product).delete()
    return redirect('shop:favorite_list')

@login_required
def favorite_list(request):
    favorites = Favorite.objects.filter(user=request.user).select_related('product')
    return render(request, 'shop/favorite_list.html', {'favorites': favorites})

@login_required
def my_products(request):
    products = Product.objects.filter(owner=request.user)  
    return render(request, 'shop/my_products.html', {'products': products})

@login_required
def reviews(request):
    reviews = Review.objects.all().order_by('-created_at')
    return render(request, 'shop/reviews.html', {'reviews': reviews})

@login_required
def add_review(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            review.save()
            return redirect('shop:reviews')
    else:
        form = ReviewForm()

    context = {'form': form}    
    return render(request, 'shop/add_review.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('shop:index')
    context = {'form': form}
    return render(request, 'registration/register.html', context)

templates/shop/add_review.html
{% extends 'shop/base.html' %}

{% block content %}
<div class="form-container">
<h1 class="editing-title">Зробити відгук</h1>
<form method="post" class="creation-form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="submit-button">Викласти</button>
</form>
</div>
{% endblock %}

templates/shop/base.html
{% load static %}

<!DOCTYPE html>
<head>
    <meta charset="utf-8" />
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>
<body>
<nav class="navbar">
    <div class="nav-links">
        <a href="{% url 'shop:index' %}">Головна сторінка</a>
        <a href="{% url 'shop:product_list' %}">Каталог</a>
        <a href="{% url 'shop:favorite_list' %}">Обране</a>
        <a href="{% url 'shop:my_products' %}">Мої оголошення</a>
        <a href="{% url 'shop:reviews' %}">Відгуки</a>
    </div>
    {% if user.is_authenticated %}
        <div class="user-info">
            Привіт, {{ user.username }}.
            <form action="{% url 'users:logout' %}" method="post">
                {% csrf_token %}
                <button type="submit">Вийти</button>
            </form>
        </div>
    {% else %}
        <div class="login-register">
            <a href="{% url 'users:login' %}" class="btn btn-primary">Увійти</a>
            <a href="{% url 'users:register' %}" class="btn btn-secondary">Зареєструватись</a>
        </div>
    {% endif %}
</nav>

{% block content %} 

{% endblock content %}

<footer class="footer">
    <div class="footer-content">
        <p>&copy; UkrMarket. Всі права захищені.</p>
    </div>
</footer>
</body>

templates/shop/create_product.html
{% extends 'shop/base.html' %}

{% block title %}Створення Нового Оголошення{% endblock %}

{% block content %}
<div class="form-container">
    <h2 class="editing-title">Створити нове оголошення</h2>
    <form method="post" enctype="multipart/form-data" class="creation-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="submit-button">Створити</button>
    </form>
</div>
{% endblock %}

templates/shop/delete_product.html
{% extends 'shop/base.html' %}

{% block title %}Видалення {{ product.title }}{% endblock %}

{% block content %}
<div class="delete-container">
    <h2>Ви дійсно хочете видалити "{{ product.title }}"?</h2>
    <form method="post" class="delete-form">
        {% csrf_token %}
        <button type="submit" class="delete-button">Підтвердити видалення</button>
        <a href="{% url 'shop:product_detail' product.id %}" class="cancel-link">Відмінити</a>
    </form>
</div>
{% endblock %}

templates/shop/edit_product.html
{% extends 'shop/base.html' %}

{% block title %} Редагування {{ product.title }}{% endblock %}

{% block content %}
<div class="form-container">
    <h2 class="editing-title">Редагувати оголошення: {{ product.title }}</h2>
    <form method="post" enctype="multipart/form-data" class="creation-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="submit-button">Завершити</button>
    </form>
</div>
{% endblock %}

templates/shop/favorite_list.html
{% extends 'shop/base.html' %}
{% load static %}

{% block content %} 
<h1 class="catalog-title">Обрані оголошення</h1>
    {% for favorite in favorites %}
    <div class="product-details">
        <div class="detail-block product-title-block">
          <h2>{{ favorite.product.title }}</h2>
        </div>
        <div class="image-block">
          <img src="{% if favorite.product.image %}{{ favorite.product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" width="400" height="350" />
        </div>
        <p class="description">Опис: {{ favorite.product.description }}</p>
        <div class="details-block">
        <p>Ціна: {{ favorite.product.price }} грн.</p>
        <p>Контакти: {{ favorite.product.contact }}</p>
        <p>Місцезнаходження: {{ favorite.product.location }}</p>
        <p>Дата створення: {{ favorite.product.created_at }}</p>
        </div>
        <div class="remove-button">
            <a href="{% url 'shop:remove_favorite' favorite.product.id %}">Прибрати</a>
        </div>
    </div>
    {% empty %}
    <div class="no-reviews">Ви ще нічого не обрали.</div>
    {% endfor %}
{% endblock %}

templates/shop/index.html
{% extends 'shop/base.html' %}
{% load static %}

{% block content %}
    <header class="hero">
        <h1>Ласкаво просимо до UkrMarket!</h1>
    </header>
    
    <section class="about-us">
        <img src='static/img/1.png'>
        <div class="text-content">
            <h2>Про нас</h2>
            <p>UkrMarket – ваш надійний партнер у світі онлайн-торгівлі.</p>
            <p>Ви можете перейти у <a href="{% url 'shop:product_list' %}">Каталог</a>, де Ви можете подивитись/продати або купити товар.</p>
            <p>На UkrMarket кожен знайде щось для себе. Ми пропонуємо широкий асортимент товарів від побутової техніки до унікальних виробів. Приєднуйтесь до нашої спільноти, де покупки перетворюються на задоволення, а продажі на ефективний бізнес.</p>
        </div>
    </section>

    <section class="about-us2">
        <img src='static/img/2.png'>
        <div class="text-content2">
            <ul>
                <h2>Чому UkrMarket?</h2>
                <li>Широкий вибір товарів: Від дрібної електроніки до автомобілів та нерухомості – у нас є все!</li>
                <li>Безпечні угоди: Наша платформа гарантує безпеку ваших транзакцій завдяки перевіреним методам оплати та сучасним системам захисту.</li>
                <li>Для покупців та продавців: Наші інструменти та послуги створені для зручності як продавців, так і покупців.</li>
                <li>Спільнота та підтримка: Приєднуйтесь до активної спільноти користувачів та отримайте підтримку від нашої служби підтримки у будь-який час.</li>
            </ul>
        </div>
    </section>

    <section class="about-us2">
        <img src='static/img/3.png'>
        <div class="text-content2">
            <h1>Контактна інформація</h1>
            <p>Якщо у вас є запитання або вам потрібна допомога, будь ласка, зв'яжіться з нами:</p>
            <ul>
                <li>Email: <a href="mailto:info@ukrmarket.com">info@ukrmarket.com</a></li>
                <li>Телефон: +380 12 345 6789</li>
                <li>Адреса: Україна, 01001, Київ, вул. Хрещатик, 1</li>
            </ul>
        </div>
    </section>
{% endblock content %}

templates/shop/my_products.html
{% extends 'shop/base.html' %}
{% load static %}

{% block content %}
<h1 class="catalog-title">Мої оголошення</h1>
<ul>
    {% for product in products %}
<div class="product-details">
        <div class="detail-block product-title-block">
            <h2>{{ product.title }}</h2>
        </div>
    <div class="image-block">
            <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
    </div>
    <p> Сторив оголошення: {{ product.owner.username }}</p>
    <p class="description">Опис: {{ product.description }}</p>
    <div class="details-block">
        <p class="detail">Ціна: {{ product.price }} грн.</p>
        <p class="detail">Контакти: {{ product.contact }}</p>
        <p class="detail">Місцезнаходження: {{ product.location }}</p>
        <p class="detail">Дата створення: {{ product.created_at }}</p>
    </div>
</div>
    {% if request.user == product.owner or request.user.is_superuser %}
    <div class="product-actions">
    <a href="{% url 'shop:edit_product' product.id %}" class="edit-link">Редагувати</a>
    <a href="{% url 'shop:delete_product' product.id %}" class="delete-link">Видалити</a>
    </div>
    {% endif %}
    
    {% empty %}
    <div class="no-reviews">У Вас ще немає створенних оголошень</div>
    {% endfor %}
</ul>
{% endblock %}

templates/shop/product_detail.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}{{ product.title }}{% endblock %}

{% block content %}
    <div class="product-details">
        <div class="detail-block product-title-block">
        <h2>{{ product.title }}</h2>
        </div>
        <div class="image-block">
            <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
        </div>
        <div class="favorite">
            <h2><a href="{% url 'shop:add_favorite' product.id %}">♥</a></h2>
        </div>
        <p> Сторив оголошення: {{ product.owner.username }}</p>
        <p class="description">Опис: {{ product.description }}</p>
        <div class="details-block">
            <p class="detail">Ціна: {{ product.price }} грн.</p>
            <p class="detail">Контакти: {{ product.contact }}</p>
            <p class="detail">Місцезнаходження: {{ product.location }}</p>
            <p class="detail">Дата створення: {{ product.created_at }}</p>
        </div>
    </div>
    {% if request.user == product.owner or request.user.is_superuser %}
        <div class="product-actions">
            <a href="{% url 'shop:edit_product' product.id %}" class="edit-link">Редагувати</a>
            <a href="{% url 'shop:delete_product' product.id %}" class="delete-link">Видалити</a>
            <a href="{% url 'shop:product_list' %}" class="back-to-list">Повернутися до каталогів</a>
        </div>
    {% endif %}
{% endblock %}

templates/shop/product_list.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}Каталог{% endblock %}

{% block content %}
<div class="catalog-container">
    <h1 class="catalog-title">Каталог</h1>
    <div class="filter-container">
        <form method="get" action="{% url 'shop:product_list' %}">
            {{ form.category.label_tag }} {{ form.category }}
            {{ form.query.label_tag }} {{ form.query }}
            <button type="submit">Фільтрувати</button>
        </form>
    </div>
    <div class="create-container">
        <a href="{% url 'shop:create_product' %}" class="btn btn-primary">Створити Нове Оголошення</a>
    </div>
    <div class="products-container">
        {% for product in products %}
            <div class="product-item">
                <a href="{% url 'shop:product_detail' product.id %}">
                    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" alt="{{ product.title }}" class="product-image">
                    <div class="product-info">
                        <h3>{{ product.title }} - {{ product.price }} грн.</h3>
                    </div>
                </a>
            </div>
        {% empty %}
        <div class="no-reviews">Тут ще немає оголошень.</div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/shop/reviews.html
{% extends 'shop/base.html' %}

{% block content %}
<h1 class="catalog-title">Відгуки користувачів</h1>
<a href="{% url 'shop:add_review' %}" class="add-review-link">Залишити відгук</a>
<ul class="reviews-list">
    {% for review in reviews %}
    <li class="review-item">
        <strong class="review-user">Користувач: {{ review.user.username }}</strong> <span class="review-date">({{ review.created_at }}):</span>
        <p class="review-rating">Оцінка: {{ review.rating }}</p>
        <p class="review-comment">Відгук: {{ review.comment }}</p>
    </li>
    {% empty %}
    <li class="no-reviews">Тут ще немає відгуків.</li>
    {% endfor %}
</ul>
{% endblock %}